plugin:
  has_options: false
  icon: res_file.png

  widgets:
    - name: claroline_mywidget1
      is_configurable: false
#    - name: claroline_mywidget2
#      is_configurable: false

  resources:
    - class: Claroline\ExampleBundle\Entity\Example
      name: claroline_example
      icon: res_file.png
      actions:
         # The name and the menu_name will be used as translation keys. Their domain is 'resource' eg resource.en.yml.
         # the action in the list of available actions for your resource.
         # The name will be passed to you by the Event manager.
         # We're aware that the right management modal will need some rework (too many rights = broken modal).

         #That one has a new menu item and a new permission
        - name: newpage
          menu_name: new_menu

         #define a new permission without the menu item
        - name: newpopup

         #define a new menu item associated to an existing permission (open is one of the base perm)
        - name: open
          menu_name: open_bis

         #this 2 menu items are bound to a new permission
        - name: example
          menu_name: ex1

        - name: example
          menu_name: ex2

  tools:
    - name: claroline_mytool
      #icon: res_text.png
      is_displayable_in_workspace: true
      is_displayable_in_desktop: true
  themes:
    - name: "ExampleBundle Theme"
      path: less/example/theme.html.twig


